#ifndef COLORFACTORY_GLOBAL_H
#define COLORFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COLORFACTORY_LIBRARY)
#  define COLORCORRECT_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define COLORCORRECT_SHARED_EXPORT Q_DECL_IMPORT
#endif

#if defined(COLORFACTORY_LIBRARY)
#  define FILTER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILTER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COLORFACTORY_GLOBAL_H
