#ifndef DEHAZECODE_GLOBAL_H
#define DEHAZECODE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEHAZECODE_LIBRARY)
#  define DARKCHANNELDEHAZOR_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define DARKCHANNELDEHAZOR_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEHAZECODE_GLOBAL_H
